### ISSUE TITLE
Build fails with `staticComponents: true` under Embroider

### ISSUE THREAD

**Issue by gilest** [sandydoo/ember-google-maps#171]
### Describe the bug
This is a new regression caused by changes in Embroider (`v2`) as in the previous version of Embroider (`v1.90`) a fully-static build was possible.

### To Reproduce

Repro [application provided here](https://github.com/gilest/gmaps-embroider-repro/commits/master). Essentially in a new Embroider app with this addon installed will fail to build when the `staticComponents: true` compat flag is enabled.

### Expected behaviour
Applications can build with static resolution thus enabling Embroider optimsations.

### Attempted solutions
Attempted to disable some of the custom tree shaking in this addon. May have another go later. Might be easier just to migrate to v2 format and cut a new major.

### Screenshots
Full stacktrace:

```
Build Error (PackagerRunner) in ../ember-google-maps/components/g-map.hbs

Module build failed (from ../../../../../../../../../Users/Giles/code/gmaps-repro/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
$TMPDIR/embroider/3836a4/ember-google-maps/components/g-map.hbs/g-map.hbs: Missing component: template in $TMPDIR/embroider/3836a4/ember-google-maps/components/g-map.hbs

    at CompatResolver.reportError (/Users/Giles/code/gmaps-repro/node_modules/@embroider/compat/src/resolver.js:219:21)
    at emit (/Users/Giles/code/gmaps-repro/node_modules/@embroider/compat/src/resolver-transform.js:39:30)
    at SubExpression (/Users/Giles/code/gmaps-repro/node_modules/@embroider/compat/src/resolver-transform.js:194:25)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9363:16)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9421:20)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitArray ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9439:20)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9418:7)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9421:20)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitArray ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9439:20)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9418:7)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitArray ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9439:20)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9418:7)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9421:20)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at visitArray ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9439:20)
    at visitKey ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9418:7)
    at visitNode ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9381:9)
    at traverse ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:9476:5)
    at preprocess ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:10802:9)
    at normalize ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:11344:15)
    at precompileJSON ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:5145:47)
    at precompile ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:5178:31)
    at Object.precompile ($TMPDIR/embroider/3836a4/gmaps-repro/node_modules/ember-source/vendor/ember/ember-template-compiler.js:16486:37)
    at insertCompiledTemplate (/Users/Giles/code/gmaps-repro/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:237:64)
    at PluginPass.CallExpression (/Users/Giles/code/gmaps-repro/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:138:25)
    at PluginPass.<anonymous> (/Users/Giles/code/gmaps-repro/node_modules/@embroider/core/src/portable-babel-launcher.js:37:29)
    at newFn (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/visitors.js:149:21)
    at NodePath._call (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/path/context.js:81:31)
    at TraversalContext.visitQueue (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/Giles/code/gmaps-repro/node_modules/@babel/traverse/lib/index.js:49:34)
```

**Comment by gilest** [comment]
Replacing `setupPreprocessorRegistry` with the following seems to resolve the issue:

```js
  setupPreprocessorRegistry(type, registry) {
    // The canvas plugin should run on `self` and `parent`.
    this._setupCanvasPlugin(registry);

    if (type === 'self') {
      // The addon plugin should run on `self`.
      this._setupAddonPlugin(registry);

      this._setupTreeshakerPlugin(registry);
    }
  },

```

**Comment by sandydoo** [comment]
@gilest, thank you so much for taking the time to write up the issue and repro!

This should be fixed on `main` now. Feel free to reopen if there's anything wrong.

I'd like to gather some feedback from the Glimmer team on https://github.com/sandydoo/ember-google-maps/issues/174 and then I'll push a new release.

**Comment by sandydoo** [comment]
Released https://github.com/sandydoo/ember-google-maps/releases/tag/v6.1.0

**Comment by gilest** [comment]
Thanks @sandydoo . I've been testing with Embroider v3 and it's working well. Granted this application only uses the `GMap` component.
